# Generated by Django 5.2.17 on 2026-08-15 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eats', '0003_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('success', 'success'), ('failed', 'failed'), ('abandoned', 'abandoned')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Eats.order')),
            ],
        ),
    ]
