# Generated by Django 5.2.17 on 2026-08-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eats', '0007_alter_order_status_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed'), ('Abandoned', 'Abandoned')], max_length=10),
        ),
    ]
