# Generated by Django 5.2.17 on 2026-10-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eats', '0009_menuitem_image_vendor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='image',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
